version: '3.9'
services:
  ontographer:
    build:
      context: ontographer
      dockerfile: Dockerfile
      args:
        PUBLIC_PATH: /
        REACT_APP_CONTEXT: production
        REACT_APP_ID: ontographer
        REACT_APP_URL: http://localhost:8080
        REACT_APP_COMPONENTS: 'YWwtc2dvdi1zZXJ2ZXI6CiAgbmFtZTogU0dvViBTZXJ2aWNlCiAgdXJsOiBodHRwczovL3huLS1zbG92bmstdGVzdC1zY2IubXZjci5nb3YuY3ovbW9kZWx1amVtZS9zbHV6Ynkvc2dvdi1zZXJ2ZXIKICBtZXRhOiB7fQphbC1kYi1zZXJ2ZXI6CiAgbmFtZTogQSBncmFwaCBkYXRhYmFzZQogIHVybDogaHR0cDovL2xvY2FsaG9zdDo3MjAxL3JlcG9zaXRvcmllcy90ZXN0T0cKICBtZXRhOiB7fQphbC1hdXRoLXNlcnZlcjoKICBuYW1lOiBPSURDIEF1dGhlbnRpY2F0aW9uIFNlcnZpY2UKICB1cmw6IGh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3JlYWxtcy9rb2RpLWRldgogIG1ldGE6IHt9CmFsLW9udG9ncmFwaGVyOgogIG5hbWU6IG9udG9HcmFwaGVyCiAgdXJsOiBodHRwczovL3Nsb3Zuw61rLmdvdi5jei9tb2RlbHVqZW1lL3YtbsOhc3Ryb2ppL29udG9ncmFwaGVyCiAgbWV0YToKICAgIHdvcmtzcGFjZVBhdGg6ICc/d29ya3NwYWNlPSVXT1JLU1BBQ0VfSVJJJScKYWwtdGVybWl0LXNlcnZlcjoKICBuYW1lOiBUZXJtSVQgYmFja2VuZAogIHVybDogaHR0cHM6Ly9leGFtcGxlLmNvbS90ZXJtaXQtYmFja2VuZAogIG1ldGE6IHt9CmFsLXRlcm1pdDoKICBuYW1lOiBUZXJtSVQKICB1cmw6IGh0dHBzOi8vc2xvdm7DrWsuZ292LmN6L21vZGVsdWplbWUvdi1uw6FzdHJvamkvdGVybWl0CiAgbWV0YToKICAgIHdvcmtzcGFjZVBhdGg6ICcjdm9jYWJ1bGFyaWVzP3dvcmtzcGFjZT0lV09SS1NQQUNFX0lSSSUnCmFsLW1pc3Npb24tY29udHJvbDoKICBuYW1lOiBNaXNzaW9uIENvbnRyb2wKICB1cmw6IGh0dHBzOi8vc2xvdm7DrWsuZ292LmN6L21vZGVsdWplbWUvCiAgbWV0YToge30KYWwtaXNzdWUtdHJhY2tlcjoKICBuYW1lOiBJc3N1ZSBUcmFja2VyCiAgdXJsOiBodHRwczovL2dpdGh1Yi5jb20vb3BlbmRhdGEtbXZjci9zZ292LWFzc2VtYmx5LWxpbmUvaXNzdWVzCiAgbWV0YToKICAgIG5ld0J1ZzogaHR0cHM6Ly9naXRodWIuY29tL29wZW5kYXRhLW12Y3Ivc2dvdi1hc3NlbWJseS1saW5lL2lzc3Vlcy9uZXc/bGFiZWxzPWJ1ZyZ0ZW1wbGF0ZT1wby1hZGF2ZWstbmEtb3ByYXZ1Lm1kJnRpdGxlPQogICAgbmV3RmVhdHVyZTogaHR0cHM6Ly9naXRodWIuY29tL29wZW5kYXRhLW12Y3Ivc2dvdi1hc3NlbWJseS1saW5lL2lzc3Vlcy9uZXc/bGFiZWxzPWVuaGFuY2VtZW50JnRlbXBsYXRlPXBvLWFkYXZlay1uYS1ub3ZvdS1mdW5rY2lvbmFsaXR1Lm1kJnRpdGxlPQo='
        REACT_APP_AUTHENTICATION: 'false'
    ports:
      - 8080:80
    restart: always
  graphdb:
    build:
      context: graphdb
      dockerfile: Dockerfile
      args:
        GRAPHDB_ZIP: graphdb-free-9.7.0-dist.zip
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=300
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.workbench.cors.origin=*
        -Dgraphdb.workbench.cors.expose-headers=*
    ports:
      - 7201:7200
    volumes:
      - ./graphdb-data:/opt/graphdb/home
    restart: always



volumes:
  graphdb-data:
